#Server Port
server.servlet.context-path=/smartrun

server.port=8495

#root path
app.root=${user.home}/smartrun/vlogix
#app.root=D:\\VLOGIX/vlogix-mes/

#Tomcat
server.tomcat.basedir=${app.root}/deployer/tomcat

#Banner
spring.main.banner-mode=LOG
spring.banner.location = smartrunbanner.txt
spring.banner.image.location= VlogixTech.jpg

# Tomcat properties
server.tomcat.max-http-form-post-size=10MB
server.tomcat.max-swallow-size=10MB

#DataSource Configuration
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
#spring.datasource.url=jdbc:mysql://192.168.1.140:3306/smartrun_pr_po?autoReconnect=true&useSSL=false
#spring.datasource.url=jdbc:mysql://45.251.34.44:3306/smartrun_bgr?autoReconnect=true&useSSL=false
#spring.datasource.password=$rd&@wspwd!


#spring.datasource.url=jdbc:mysql://192.168.1.8:3306/smartrun_bgr?autoReconnect=true&useSSL=false
#spring.datasource.username=vmfg
#spring.datasource.password=vmfgpwd!

#Connecting Local

spring.datasource.url=jdbc:mysql://localhost:3306/smartrun_bgr_sandbox?autoReconnect=true&useSSL=false&allowPublicKeyRetrieval=true&sessionVariables=sql_mode='STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION'
#spring.datasource.url=jdbc:mysql://localhost:3306/smartrun_bgr?autoReconnect=true&useSSL=false&allowPublicKeyRetrieval=true&sessionVariables=sql_mode='STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION'
#spring.datasource.url=jdbc:mysql://192.168.1.5:3306/smartrun_bgr?autoReconnect=true&useSSL=false&allowPublicKeyRetrieval=true
#spring.datasource.url=jdbc:mysql://192.168.3.38/smartrun_bgr?autoReconnect=true&useSSL=false
#spring.datasource.username=bgradmin
#spring.datasource.password=BGR@123
#This id for test server
#spring.datasource.username=root
#spring.datasource.password=root
#FOR TEST
spring.datasource.username=vmfg
spring.datasource.password=$rd&@wspwd!
#spring.datasource.url=jdbc:mysql://192.168.0.46:3306/smartrun_bgr?autoReconnect=true&useSSL=false
#spring.datasource.username=vmfg
#spring.datasource.password=vmfgpwd!

#Connecting Prod

#spring.datasource.url=jdbc:mysql://13.235.170.46/smartrun_bgr?autoReconnect=true&useSSL=false
#spring.datasource.username=vmfg
#spring.datasource.password=JiQAGE4d8;ru

#spring.datasource.url=jdbc:mysql://192.168.1.140:3306/sr_proj_management?autoReconnect=true&useSSL=false
#spring.datasource.url=jdbc:mysql://localhost:3306/modine_inventory?autoReconnect=true&useSSL=false
#spring.datasource.url=jdbc:mysql://192.168.1.140:3306/sr_proj_management?autoReconnect=true&useSSL=false
#spring.datasource.url=jdbc:mysql://localhost:3306/sr_140_proj?autoReconnect=true&useSSL=false
#spring.datasource.url=jdbc:mysql://localhost:3306/sr_proj_management?autoReconnect=true&useSSL=false
#spring.datasource.url=jdbc:mysql://45.251.34.44:3306/sr_proj_management?autoReconnect=true&useSSL=false
#spring.datasource.url=jdbc:mysql://localhost:3306/sr_proj_manage?autoReconnect=true&useSSL=false
#spring.datasource.url=jdbc:mysql://localhost:3306/smartrun_pr_po?autoReconnect=true&useSSL=false
#spring.datasource.username=root
#spring.datasource.password=root

#Build Server
#spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
#spring.datasource.url=jdbc:mysql://172.17.1.171:3306/smartrun_job?autoReconnect=true&useSSL=false
#spring.datasource.username=vmfg
#spring.datasource.password=vmfgdtvspwd!

#URL for Machine condition check sheet:
app.mcsheeturl = http://localhost:8587/vmfg/mqttsender/
spring.mvc.pathmatch.matching-strategy = ANT_PATH_MATCHER

#Connection Pool Configuration
spring.datasource.tomcat.initial-size=20
spring.datasource.tomcat.max-wait=20000
spring.datasource.tomcat.max-active=50
spring.datasource.tomcat.max-idle=20
spring.datasource.tomcat.min-idle=15
spring.datasource.tomcat.default-auto-commit=true
spring.datasource.tomcat.test-on-borrow=false
spring.datasource.tomcat.testWhileIdle = true
spring.datasource.tomcat.timeBetweenEvictionRunsMillis = 300000
spring.datasource.tomcat.validationQuery = SELECT 1

#search multipart
spring.http.multipart.max-file-size=10MB
spring.http.multipart.max-request-size=10MB

spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB


#logging Configuration USED IN LOGBACK.xml
logging.config=classpath:logback-prod.xml
logging.file.name=smartrun-40-log/

jwt.secret =SMARTRUNMESSOLUTION



app.report.dc.qrimage=${app.root}/Modine/LblQrImage/
app.report.dc.lable=${app.root}/Modine/LblPdf/